// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVwHnFcXmJz7Z4-nIhot8ERdi1Ba3-La8',
    appId: '1:328420207335:web:0e0e04eac39652f9201042',
    messagingSenderId: '328420207335',
    projectId: 'myblogapp-f2740',
    authDomain: 'myblogapp-f2740.firebaseapp.com',
    storageBucket: 'myblogapp-f2740.firebasestorage.app',
    measurementId: 'G-QJXW20PMCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNK6Tbwe2CQ27GXpyyih9nU5R_DXJ079E',
    appId: '1:328420207335:android:ec33e45b91821425201042',
    messagingSenderId: '328420207335',
    projectId: 'myblogapp-f2740',
    storageBucket: 'myblogapp-f2740.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0SScWxUX97mHpdkZJ_VhtvBBACxOejKY',
    appId: '1:328420207335:ios:dcae510e478aa45f201042',
    messagingSenderId: '328420207335',
    projectId: 'myblogapp-f2740',
    storageBucket: 'myblogapp-f2740.firebasestorage.app',
    iosBundleId: 'com.example.myBlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0SScWxUX97mHpdkZJ_VhtvBBACxOejKY',
    appId: '1:328420207335:ios:dcae510e478aa45f201042',
    messagingSenderId: '328420207335',
    projectId: 'myblogapp-f2740',
    storageBucket: 'myblogapp-f2740.firebasestorage.app',
    iosBundleId: 'com.example.myBlogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVwHnFcXmJz7Z4-nIhot8ERdi1Ba3-La8',
    appId: '1:328420207335:web:eaf4552661a648f6201042',
    messagingSenderId: '328420207335',
    projectId: 'myblogapp-f2740',
    authDomain: 'myblogapp-f2740.firebaseapp.com',
    storageBucket: 'myblogapp-f2740.firebasestorage.app',
    measurementId: 'G-6TP2QZDQR5',
  );

}